version: '3.8'
services:
    app:
        container_name: push-notif-server
        command: node -r esm bin/app.js
        build:
            context: '.'
            dockerfile: './docker/Dockerfile'
        depends_on:
            - db
        ports:
            - '5000:5000'
        environment:
            - NODE_ENV=production
            - PORT=5000
    db:
        container_name: postgres
        image: postgres:12-alpine
        ports:
            - '5433:5432'
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: pns
