version: '3.8'
services:
    app:
        container_name: push-notif-server
        build:
            context: '.'
            dockerfile: './docker/Dockerfile'
        depends_on:
            - postgres
        ports:
            - '5000:5000'
    postgres:
        container_name: postgres
        image: postgres:12-alpine
        ports:
            - '5433:5432'
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: pns
